#!/usr/extra/bin/ksh
# MAKEMODCURRENT
PN=${0##*/}
ex=1
if [[ -d mod ]] ; then
  typeset MF=
  for MX in "${@}" ; do
    case ${MX} in
    *.ccm)
      MF=${MX}
      ;;
    *.o)
      R=${MX%.*}
      MF="${R}.ccm"
      ;;
    *)
      MF="${MX%.*}.ccm"
      ;;
    esac
    if [[ ! -r ${MF} ]] ; then
      if [[ -r mod/${MF} ]] ; then
        ln -f mod/${MF} .
	ex=${?}
      else
        print -u 2 -- "${PN}: requested module not in repository"
      fi
    fi
  done
else
  print -u 2 -- "${PN}: no module directory present"
fi
return ${ex}

