#!/usr/extra/bin/ksh
# MKLINKS

LOCPROG=macsysdata.x
CMDS=
CMDS+=" sysname systype sysrelease sysversion systime sysuuid sysid "
CMDS+=" sysversionx "
CMDS+=" release nodename version "
CMDS+=" architecture machine platform cpuvendor "
CMDS+=" nisdomain symfile hostid lax "
CMDS+=" unixtime "

TDIRS=" /usr/extra /usr/local /opt/local "

function linkdir {
  typeset TDIR=${1}
  for C in ${CMDS} ; do
    ln -f ${LOCPROG} ${TDIR}/bin/${C}
  done
}

if [[ -x "${LOCPROG}" ]] ; then
  for D in ${TDIRS} ; do
    if [[ -d "${D}" ]] ; then
      linkdir $D
    else
      print -u 2 -- "target directory not present"
      break ;
    fi
  done
else
  print -u 2 -- "program not made"
fi


