#!/usr/extra/bin/ksh
# MKLINKS

LOCPROG=macsysdata.x
CMDS=
CMDS+=" sysname release nodename version "
CMDS+=" architecture machine platform systype "
CMDS+=" nisdomain hostid lax "

TDIRS=" /usr/extra /usr/local /opt/local "

function linkdir {
  typeset TDIR=${1}
  for C in ${CMDS} ; do
    ln -f ${LOCPROG} ${TDIR}/bin/${C}
  done
}

if [[ -x "${LOCPROG}" ]] ; then
  for D in ${TDIRS} ; do
    if [[ -d "${D}" ]] ; then
      linkdir $D
    else
      print -u 2 -- "target directory not present"
      break ;
    fi
  done
else
  print -u 2 -- "program not made"
fi


