#!/usr/local/bin/ksh
# MKLINKS (showterms)

CMDS=" showterms "
LOCPROG=showterms.x

: ${HOME:=$( userhome )}
: ${EXTRA:=/usr/extra}
: ${USRLOCAL:=/usr/local}
: ${LOCAL:=/opt/local}

TDIRS=" ${EXTRA} ${USRLOCAL} "

function linkdir {
  typeset TDIR=${1}
  for C in ${CMDS} ; do
    ln -f ${LOCPROG} ${TDIR}/bin/${C}
  done
} # end function

if [[ -x "${LOCPROG}" ]] ; then
  for D in ${TDIRS} ; do
    if [[ -d "${D}" ]] ; then
      linkdir $D
    else
      print -u 2 -- "target directory not present"
      break ;
    fi
  done
else
  print -u 2 -- "program not made"
fi

